package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepUserInfoViewId generated by hbm2java
 */
public class RepUserInfoViewId implements java.io.Serializable {

	private int userNo;
	private String userUid;
	private String userEmail;
	private String userName;
	private String userSex;
	private String userCert;
	private String userResidence;
	private Integer userAddrDisNo;
	private String userAddrName;
	private String userAddrPos;
	private String userIntentDisNo;
	private Integer userEducationNo;
	private String educationDictName;
	private Integer userExpNo;
	private String jobExpDictName;
	private String userIntention;
	private String userPhone;
	private String userBynow;
	private Integer userAge;
	private String userSkill;
	private String userContent;
	private String reserved01;
	private String reserved02;

	public RepUserInfoViewId() {
	}

	public RepUserInfoViewId(int userNo, String userUid, String userEmail) {
		this.userNo = userNo;
		this.userUid = userUid;
		this.userEmail = userEmail;
	}

	public RepUserInfoViewId(int userNo, String userUid, String userEmail,
			String userName, String userSex, String userCert,
			String userResidence, Integer userAddrDisNo, String userAddrName,
			String userAddrPos, String userIntentDisNo,
			Integer userEducationNo, String educationDictName,
			Integer userExpNo, String jobExpDictName, String userIntention,
			String userPhone, String userBynow, Integer userAge,
			String userSkill, String userContent, String reserved01,
			String reserved02) {
		this.userNo = userNo;
		this.userUid = userUid;
		this.userEmail = userEmail;
		this.userName = userName;
		this.userSex = userSex;
		this.userCert = userCert;
		this.userResidence = userResidence;
		this.userAddrDisNo = userAddrDisNo;
		this.userAddrName = userAddrName;
		this.userAddrPos = userAddrPos;
		this.userIntentDisNo = userIntentDisNo;
		this.userEducationNo = userEducationNo;
		this.educationDictName = educationDictName;
		this.userExpNo = userExpNo;
		this.jobExpDictName = jobExpDictName;
		this.userIntention = userIntention;
		this.userPhone = userPhone;
		this.userBynow = userBynow;
		this.userAge = userAge;
		this.userSkill = userSkill;
		this.userContent = userContent;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
	}

	public int getUserNo() {
		return this.userNo;
	}

	public void setUserNo(int userNo) {
		this.userNo = userNo;
	}

	public String getUserUid() {
		return this.userUid;
	}

	public void setUserUid(String userUid) {
		this.userUid = userUid;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	public String getUserCert() {
		return this.userCert;
	}

	public void setUserCert(String userCert) {
		this.userCert = userCert;
	}

	public String getUserResidence() {
		return this.userResidence;
	}

	public void setUserResidence(String userResidence) {
		this.userResidence = userResidence;
	}

	public Integer getUserAddrDisNo() {
		return this.userAddrDisNo;
	}

	public void setUserAddrDisNo(Integer userAddrDisNo) {
		this.userAddrDisNo = userAddrDisNo;
	}

	public String getUserAddrName() {
		return this.userAddrName;
	}

	public void setUserAddrName(String userAddrName) {
		this.userAddrName = userAddrName;
	}

	public String getUserAddrPos() {
		return this.userAddrPos;
	}

	public void setUserAddrPos(String userAddrPos) {
		this.userAddrPos = userAddrPos;
	}

	public String getUserIntentDisNo() {
		return this.userIntentDisNo;
	}

	public void setUserIntentDisNo(String userIntentDisNo) {
		this.userIntentDisNo = userIntentDisNo;
	}

	public Integer getUserEducationNo() {
		return this.userEducationNo;
	}

	public void setUserEducationNo(Integer userEducationNo) {
		this.userEducationNo = userEducationNo;
	}

	public String getEducationDictName() {
		return this.educationDictName;
	}

	public void setEducationDictName(String educationDictName) {
		this.educationDictName = educationDictName;
	}

	public Integer getUserExpNo() {
		return this.userExpNo;
	}

	public void setUserExpNo(Integer userExpNo) {
		this.userExpNo = userExpNo;
	}

	public String getJobExpDictName() {
		return this.jobExpDictName;
	}

	public void setJobExpDictName(String jobExpDictName) {
		this.jobExpDictName = jobExpDictName;
	}

	public String getUserIntention() {
		return this.userIntention;
	}

	public void setUserIntention(String userIntention) {
		this.userIntention = userIntention;
	}

	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserBynow() {
		return this.userBynow;
	}

	public void setUserBynow(String userBynow) {
		this.userBynow = userBynow;
	}

	public Integer getUserAge() {
		return this.userAge;
	}

	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	public String getUserSkill() {
		return this.userSkill;
	}

	public void setUserSkill(String userSkill) {
		this.userSkill = userSkill;
	}

	public String getUserContent() {
		return this.userContent;
	}

	public void setUserContent(String userContent) {
		this.userContent = userContent;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepUserInfoViewId))
			return false;
		RepUserInfoViewId castOther = (RepUserInfoViewId) other;

		return (this.getUserNo() == castOther.getUserNo())
				&& ((this.getUserUid() == castOther.getUserUid()) || (this
						.getUserUid() != null && castOther.getUserUid() != null && this
						.getUserUid().equals(castOther.getUserUid())))
				&& ((this.getUserEmail() == castOther.getUserEmail()) || (this
						.getUserEmail() != null
						&& castOther.getUserEmail() != null && this
						.getUserEmail().equals(castOther.getUserEmail())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserSex() == castOther.getUserSex()) || (this
						.getUserSex() != null && castOther.getUserSex() != null && this
						.getUserSex().equals(castOther.getUserSex())))
				&& ((this.getUserCert() == castOther.getUserCert()) || (this
						.getUserCert() != null
						&& castOther.getUserCert() != null && this
						.getUserCert().equals(castOther.getUserCert())))
				&& ((this.getUserResidence() == castOther.getUserResidence()) || (this
						.getUserResidence() != null
						&& castOther.getUserResidence() != null && this
						.getUserResidence()
						.equals(castOther.getUserResidence())))
				&& ((this.getUserAddrDisNo() == castOther.getUserAddrDisNo()) || (this
						.getUserAddrDisNo() != null
						&& castOther.getUserAddrDisNo() != null && this
						.getUserAddrDisNo()
						.equals(castOther.getUserAddrDisNo())))
				&& ((this.getUserAddrName() == castOther.getUserAddrName()) || (this
						.getUserAddrName() != null
						&& castOther.getUserAddrName() != null && this
						.getUserAddrName().equals(castOther.getUserAddrName())))
				&& ((this.getUserAddrPos() == castOther.getUserAddrPos()) || (this
						.getUserAddrPos() != null
						&& castOther.getUserAddrPos() != null && this
						.getUserAddrPos().equals(castOther.getUserAddrPos())))
				&& ((this.getUserIntentDisNo() == castOther
						.getUserIntentDisNo()) || (this.getUserIntentDisNo() != null
						&& castOther.getUserIntentDisNo() != null && this
						.getUserIntentDisNo().equals(
								castOther.getUserIntentDisNo())))
				&& ((this.getUserEducationNo() == castOther
						.getUserEducationNo()) || (this.getUserEducationNo() != null
						&& castOther.getUserEducationNo() != null && this
						.getUserEducationNo().equals(
								castOther.getUserEducationNo())))
				&& ((this.getEducationDictName() == castOther
						.getEducationDictName()) || (this
						.getEducationDictName() != null
						&& castOther.getEducationDictName() != null && this
						.getEducationDictName().equals(
								castOther.getEducationDictName())))
				&& ((this.getUserExpNo() == castOther.getUserExpNo()) || (this
						.getUserExpNo() != null
						&& castOther.getUserExpNo() != null && this
						.getUserExpNo().equals(castOther.getUserExpNo())))
				&& ((this.getJobExpDictName() == castOther.getJobExpDictName()) || (this
						.getJobExpDictName() != null
						&& castOther.getJobExpDictName() != null && this
						.getJobExpDictName().equals(
								castOther.getJobExpDictName())))
				&& ((this.getUserIntention() == castOther.getUserIntention()) || (this
						.getUserIntention() != null
						&& castOther.getUserIntention() != null && this
						.getUserIntention()
						.equals(castOther.getUserIntention())))
				&& ((this.getUserPhone() == castOther.getUserPhone()) || (this
						.getUserPhone() != null
						&& castOther.getUserPhone() != null && this
						.getUserPhone().equals(castOther.getUserPhone())))
				&& ((this.getUserBynow() == castOther.getUserBynow()) || (this
						.getUserBynow() != null
						&& castOther.getUserBynow() != null && this
						.getUserBynow().equals(castOther.getUserBynow())))
				&& ((this.getUserAge() == castOther.getUserAge()) || (this
						.getUserAge() != null && castOther.getUserAge() != null && this
						.getUserAge().equals(castOther.getUserAge())))
				&& ((this.getUserSkill() == castOther.getUserSkill()) || (this
						.getUserSkill() != null
						&& castOther.getUserSkill() != null && this
						.getUserSkill().equals(castOther.getUserSkill())))
				&& ((this.getUserContent() == castOther.getUserContent()) || (this
						.getUserContent() != null
						&& castOther.getUserContent() != null && this
						.getUserContent().equals(castOther.getUserContent())))
				&& ((this.getReserved01() == castOther.getReserved01()) || (this
						.getReserved01() != null
						&& castOther.getReserved01() != null && this
						.getReserved01().equals(castOther.getReserved01())))
				&& ((this.getReserved02() == castOther.getReserved02()) || (this
						.getReserved02() != null
						&& castOther.getReserved02() != null && this
						.getReserved02().equals(castOther.getReserved02())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserNo();
		result = 37 * result
				+ (getUserUid() == null ? 0 : this.getUserUid().hashCode());
		result = 37 * result
				+ (getUserEmail() == null ? 0 : this.getUserEmail().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getUserSex() == null ? 0 : this.getUserSex().hashCode());
		result = 37 * result
				+ (getUserCert() == null ? 0 : this.getUserCert().hashCode());
		result = 37
				* result
				+ (getUserResidence() == null ? 0 : this.getUserResidence()
						.hashCode());
		result = 37
				* result
				+ (getUserAddrDisNo() == null ? 0 : this.getUserAddrDisNo()
						.hashCode());
		result = 37
				* result
				+ (getUserAddrName() == null ? 0 : this.getUserAddrName()
						.hashCode());
		result = 37
				* result
				+ (getUserAddrPos() == null ? 0 : this.getUserAddrPos()
						.hashCode());
		result = 37
				* result
				+ (getUserIntentDisNo() == null ? 0 : this.getUserIntentDisNo()
						.hashCode());
		result = 37
				* result
				+ (getUserEducationNo() == null ? 0 : this.getUserEducationNo()
						.hashCode());
		result = 37
				* result
				+ (getEducationDictName() == null ? 0 : this
						.getEducationDictName().hashCode());
		result = 37 * result
				+ (getUserExpNo() == null ? 0 : this.getUserExpNo().hashCode());
		result = 37
				* result
				+ (getJobExpDictName() == null ? 0 : this.getJobExpDictName()
						.hashCode());
		result = 37
				* result
				+ (getUserIntention() == null ? 0 : this.getUserIntention()
						.hashCode());
		result = 37 * result
				+ (getUserPhone() == null ? 0 : this.getUserPhone().hashCode());
		result = 37 * result
				+ (getUserBynow() == null ? 0 : this.getUserBynow().hashCode());
		result = 37 * result
				+ (getUserAge() == null ? 0 : this.getUserAge().hashCode());
		result = 37 * result
				+ (getUserSkill() == null ? 0 : this.getUserSkill().hashCode());
		result = 37
				* result
				+ (getUserContent() == null ? 0 : this.getUserContent()
						.hashCode());
		result = 37
				* result
				+ (getReserved01() == null ? 0 : this.getReserved01()
						.hashCode());
		result = 37
				* result
				+ (getReserved02() == null ? 0 : this.getReserved02()
						.hashCode());
		return result;
	}

}
