package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepEntJobInfoView generated by hbm2java
 */
public class RepEntJobInfoView implements java.io.Serializable {

	private RepEntJobInfoViewId id;

	public RepEntJobInfoView() {
	}

	public RepEntJobInfoView(RepEntJobInfoViewId id) {
		this.id = id;
	}

	public RepEntJobInfoViewId getId() {
		return this.id;
	}

	public void setId(RepEntJobInfoViewId id) {
		this.id = id;
	}

}
