package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RepEntFavourite generated by hbm2java
 */
public class RepEntFavourite implements java.io.Serializable {

	private RepEntFavouriteId id;
	private Date submittime;
	private String favouriteName;
	private String favouriteType;
	private String reserved01;

	public RepEntFavourite() {
	}

	public RepEntFavourite(RepEntFavouriteId id) {
		this.id = id;
	}

	public RepEntFavourite(RepEntFavouriteId id, Date submittime,
			String favouriteName, String favouriteType, String reserved01) {
		this.id = id;
		this.submittime = submittime;
		this.favouriteName = favouriteName;
		this.favouriteType = favouriteType;
		this.reserved01 = reserved01;
	}

	public RepEntFavouriteId getId() {
		return this.id;
	}

	public void setId(RepEntFavouriteId id) {
		this.id = id;
	}

	public Date getSubmittime() {
		return this.submittime;
	}

	public void setSubmittime(Date submittime) {
		this.submittime = submittime;
	}

	public String getFavouriteName() {
		return this.favouriteName;
	}

	public void setFavouriteName(String favouriteName) {
		this.favouriteName = favouriteName;
	}

	public String getFavouriteType() {
		return this.favouriteType;
	}

	public void setFavouriteType(String favouriteType) {
		this.favouriteType = favouriteType;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

}
