package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * Test1 generated by hbm2java
 */
public class Test1 implements java.io.Serializable {

	private int userno;
	private String username;

	public Test1() {
	}

	public Test1(int userno) {
		this.userno = userno;
	}

	public Test1(int userno, String username) {
		this.userno = userno;
		this.username = username;
	}

	public int getUserno() {
		return this.userno;
	}

	public void setUserno(int userno) {
		this.userno = userno;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
