package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepUserSupple generated by hbm2java
 */
public class RepUserSupple implements java.io.Serializable {

	private Integer gid;
	private int userno;
	private String supInfo;
	private String supContent;
	private String reserved01;
	private String reserved02;

	public RepUserSupple() {
	}

	public RepUserSupple(int userno) {
		this.userno = userno;
	}

	public RepUserSupple(int userno, String supInfo, String supContent,
			String reserved01, String reserved02) {
		this.userno = userno;
		this.supInfo = supInfo;
		this.supContent = supContent;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public int getUserno() {
		return this.userno;
	}

	public void setUserno(int userno) {
		this.userno = userno;
	}

	public String getSupInfo() {
		return this.supInfo;
	}

	public void setSupInfo(String supInfo) {
		this.supInfo = supInfo;
	}

	public String getSupContent() {
		return this.supContent;
	}

	public void setSupContent(String supContent) {
		this.supContent = supContent;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

}
