package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepAdminJobSalaryDict generated by hbm2java
 */
public class RepAdminJobSalaryDict implements java.io.Serializable {

	private int jobSalaryDictNo;
	private String jobSalaryDictName;
	private String reserved01;

	public RepAdminJobSalaryDict() {
	}

	public RepAdminJobSalaryDict(int jobSalaryDictNo, String jobSalaryDictName) {
		this.jobSalaryDictNo = jobSalaryDictNo;
		this.jobSalaryDictName = jobSalaryDictName;
	}

	public RepAdminJobSalaryDict(int jobSalaryDictNo, String jobSalaryDictName,
			String reserved01) {
		this.jobSalaryDictNo = jobSalaryDictNo;
		this.jobSalaryDictName = jobSalaryDictName;
		this.reserved01 = reserved01;
	}

	public int getJobSalaryDictNo() {
		return this.jobSalaryDictNo;
	}

	public void setJobSalaryDictNo(int jobSalaryDictNo) {
		this.jobSalaryDictNo = jobSalaryDictNo;
	}

	public String getJobSalaryDictName() {
		return this.jobSalaryDictName;
	}

	public void setJobSalaryDictName(String jobSalaryDictName) {
		this.jobSalaryDictName = jobSalaryDictName;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

}
