package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepAdminEntScaleDict generated by hbm2java
 */
public class RepAdminEntScaleDict implements java.io.Serializable {

	private int scaleNo;
	private String scaleName;
	private String reserved01;

	public RepAdminEntScaleDict() {
	}

	public RepAdminEntScaleDict(int scaleNo) {
		this.scaleNo = scaleNo;
	}

	public RepAdminEntScaleDict(int scaleNo, String scaleName, String reserved01) {
		this.scaleNo = scaleNo;
		this.scaleName = scaleName;
		this.reserved01 = reserved01;
	}

	public int getScaleNo() {
		return this.scaleNo;
	}

	public void setScaleNo(int scaleNo) {
		this.scaleNo = scaleNo;
	}

	public String getScaleName() {
		return this.scaleName;
	}

	public void setScaleName(String scaleName) {
		this.scaleName = scaleName;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

}
