package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepAdminProIntentionDict generated by hbm2java
 */
public class RepAdminProIntentionDict implements java.io.Serializable {

	private int jobIntentionDictNo;
	private String jobIntentionDictName;
	private int jobIntentionDictFatherId;
	private String reserved01;

	public RepAdminProIntentionDict() {
	}

	public RepAdminProIntentionDict(int jobIntentionDictNo,
			String jobIntentionDictName, int jobIntentionDictFatherId) {
		this.jobIntentionDictNo = jobIntentionDictNo;
		this.jobIntentionDictName = jobIntentionDictName;
		this.jobIntentionDictFatherId = jobIntentionDictFatherId;
	}

	public RepAdminProIntentionDict(int jobIntentionDictNo,
			String jobIntentionDictName, int jobIntentionDictFatherId,
			String reserved01) {
		this.jobIntentionDictNo = jobIntentionDictNo;
		this.jobIntentionDictName = jobIntentionDictName;
		this.jobIntentionDictFatherId = jobIntentionDictFatherId;
		this.reserved01 = reserved01;
	}

	public int getJobIntentionDictNo() {
		return this.jobIntentionDictNo;
	}

	public void setJobIntentionDictNo(int jobIntentionDictNo) {
		this.jobIntentionDictNo = jobIntentionDictNo;
	}

	public String getJobIntentionDictName() {
		return this.jobIntentionDictName;
	}

	public void setJobIntentionDictName(String jobIntentionDictName) {
		this.jobIntentionDictName = jobIntentionDictName;
	}

	public int getJobIntentionDictFatherId() {
		return this.jobIntentionDictFatherId;
	}

	public void setJobIntentionDictFatherId(int jobIntentionDictFatherId) {
		this.jobIntentionDictFatherId = jobIntentionDictFatherId;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

}
