package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepEntJobUserId generated by hbm2java
 */
public class RepEntJobUserId implements java.io.Serializable {

	private int userNo;
	private int jobNo;

	public RepEntJobUserId() {
	}

	public RepEntJobUserId(int userNo, int jobNo) {
		this.userNo = userNo;
		this.jobNo = jobNo;
	}

	public int getUserNo() {
		return this.userNo;
	}

	public void setUserNo(int userNo) {
		this.userNo = userNo;
	}

	public int getJobNo() {
		return this.jobNo;
	}

	public void setJobNo(int jobNo) {
		this.jobNo = jobNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepEntJobUserId))
			return false;
		RepEntJobUserId castOther = (RepEntJobUserId) other;

		return (this.getUserNo() == castOther.getUserNo())
				&& (this.getJobNo() == castOther.getJobNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserNo();
		result = 37 * result + this.getJobNo();
		return result;
	}

}
