package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepEntInfoViewId generated by hbm2java
 */
public class RepEntInfoViewId implements java.io.Serializable {

	private int entNo;
	private String entName;
	private String entUid;
	private String entType;
	private Integer entPcode;
	private String entEmail;
	private String entContactMan;
	private String entContactPhone;
	private String entContactAddr;
	private int entTypeEconomyNo;
	private String entTypeEconomyName;
	private int entTypeTradeNo;
	private String entTypeTradeName;
	private int entAddrDisNo;
	private String communityAddr;
	private String entSercurityNum;
	private String entScaleNo;
	private String scaleName;
	private String entOCode;
	private String entCertUrlSer;
	private String entCertUrlO;
	private String entCertUrlLicence;
	private String entContent;
	private String reserved01;
	private Integer reserved02;

	public RepEntInfoViewId() {
	}

	public RepEntInfoViewId(int entNo, String entName, String entUid,
			String entEmail, int entTypeEconomyNo, int entTypeTradeNo,
			int entAddrDisNo) {
		this.entNo = entNo;
		this.entName = entName;
		this.entUid = entUid;
		this.entEmail = entEmail;
		this.entTypeEconomyNo = entTypeEconomyNo;
		this.entTypeTradeNo = entTypeTradeNo;
		this.entAddrDisNo = entAddrDisNo;
	}

	public RepEntInfoViewId(int entNo, String entName, String entUid,
			String entType, Integer entPcode, String entEmail,
			String entContactMan, String entContactPhone,
			String entContactAddr, int entTypeEconomyNo,
			String entTypeEconomyName, int entTypeTradeNo,
			String entTypeTradeName, int entAddrDisNo, String communityAddr,
			String entSercurityNum, String entScaleNo, String scaleName,
			String entOCode, String entCertUrlSer, String entCertUrlO,
			String entCertUrlLicence, String entContent, String reserved01,
			Integer reserved02) {
		this.entNo = entNo;
		this.entName = entName;
		this.entUid = entUid;
		this.entType = entType;
		this.entPcode = entPcode;
		this.entEmail = entEmail;
		this.entContactMan = entContactMan;
		this.entContactPhone = entContactPhone;
		this.entContactAddr = entContactAddr;
		this.entTypeEconomyNo = entTypeEconomyNo;
		this.entTypeEconomyName = entTypeEconomyName;
		this.entTypeTradeNo = entTypeTradeNo;
		this.entTypeTradeName = entTypeTradeName;
		this.entAddrDisNo = entAddrDisNo;
		this.communityAddr = communityAddr;
		this.entSercurityNum = entSercurityNum;
		this.entScaleNo = entScaleNo;
		this.scaleName = scaleName;
		this.entOCode = entOCode;
		this.entCertUrlSer = entCertUrlSer;
		this.entCertUrlO = entCertUrlO;
		this.entCertUrlLicence = entCertUrlLicence;
		this.entContent = entContent;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
	}

	public int getEntNo() {
		return this.entNo;
	}

	public void setEntNo(int entNo) {
		this.entNo = entNo;
	}

	public String getEntName() {
		return this.entName;
	}

	public void setEntName(String entName) {
		this.entName = entName;
	}

	public String getEntUid() {
		return this.entUid;
	}

	public void setEntUid(String entUid) {
		this.entUid = entUid;
	}

	public String getEntType() {
		return this.entType;
	}

	public void setEntType(String entType) {
		this.entType = entType;
	}

	public Integer getEntPcode() {
		return this.entPcode;
	}

	public void setEntPcode(Integer entPcode) {
		this.entPcode = entPcode;
	}

	public String getEntEmail() {
		return this.entEmail;
	}

	public void setEntEmail(String entEmail) {
		this.entEmail = entEmail;
	}

	public String getEntContactMan() {
		return this.entContactMan;
	}

	public void setEntContactMan(String entContactMan) {
		this.entContactMan = entContactMan;
	}

	public String getEntContactPhone() {
		return this.entContactPhone;
	}

	public void setEntContactPhone(String entContactPhone) {
		this.entContactPhone = entContactPhone;
	}

	public String getEntContactAddr() {
		return this.entContactAddr;
	}

	public void setEntContactAddr(String entContactAddr) {
		this.entContactAddr = entContactAddr;
	}

	public int getEntTypeEconomyNo() {
		return this.entTypeEconomyNo;
	}

	public void setEntTypeEconomyNo(int entTypeEconomyNo) {
		this.entTypeEconomyNo = entTypeEconomyNo;
	}

	public String getEntTypeEconomyName() {
		return this.entTypeEconomyName;
	}

	public void setEntTypeEconomyName(String entTypeEconomyName) {
		this.entTypeEconomyName = entTypeEconomyName;
	}

	public int getEntTypeTradeNo() {
		return this.entTypeTradeNo;
	}

	public void setEntTypeTradeNo(int entTypeTradeNo) {
		this.entTypeTradeNo = entTypeTradeNo;
	}

	public String getEntTypeTradeName() {
		return this.entTypeTradeName;
	}

	public void setEntTypeTradeName(String entTypeTradeName) {
		this.entTypeTradeName = entTypeTradeName;
	}

	public int getEntAddrDisNo() {
		return this.entAddrDisNo;
	}

	public void setEntAddrDisNo(int entAddrDisNo) {
		this.entAddrDisNo = entAddrDisNo;
	}

	public String getCommunityAddr() {
		return this.communityAddr;
	}

	public void setCommunityAddr(String communityAddr) {
		this.communityAddr = communityAddr;
	}

	public String getEntSercurityNum() {
		return this.entSercurityNum;
	}

	public void setEntSercurityNum(String entSercurityNum) {
		this.entSercurityNum = entSercurityNum;
	}

	public String getEntScaleNo() {
		return this.entScaleNo;
	}

	public void setEntScaleNo(String entScaleNo) {
		this.entScaleNo = entScaleNo;
	}

	public String getScaleName() {
		return this.scaleName;
	}

	public void setScaleName(String scaleName) {
		this.scaleName = scaleName;
	}

	public String getEntOCode() {
		return this.entOCode;
	}

	public void setEntOCode(String entOCode) {
		this.entOCode = entOCode;
	}

	public String getEntCertUrlSer() {
		return this.entCertUrlSer;
	}

	public void setEntCertUrlSer(String entCertUrlSer) {
		this.entCertUrlSer = entCertUrlSer;
	}

	public String getEntCertUrlO() {
		return this.entCertUrlO;
	}

	public void setEntCertUrlO(String entCertUrlO) {
		this.entCertUrlO = entCertUrlO;
	}

	public String getEntCertUrlLicence() {
		return this.entCertUrlLicence;
	}

	public void setEntCertUrlLicence(String entCertUrlLicence) {
		this.entCertUrlLicence = entCertUrlLicence;
	}

	public String getEntContent() {
		return this.entContent;
	}

	public void setEntContent(String entContent) {
		this.entContent = entContent;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public Integer getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(Integer reserved02) {
		this.reserved02 = reserved02;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepEntInfoViewId))
			return false;
		RepEntInfoViewId castOther = (RepEntInfoViewId) other;

		return (this.getEntNo() == castOther.getEntNo())
				&& ((this.getEntName() == castOther.getEntName()) || (this
						.getEntName() != null && castOther.getEntName() != null && this
						.getEntName().equals(castOther.getEntName())))
				&& ((this.getEntUid() == castOther.getEntUid()) || (this
						.getEntUid() != null && castOther.getEntUid() != null && this
						.getEntUid().equals(castOther.getEntUid())))
				&& ((this.getEntType() == castOther.getEntType()) || (this
						.getEntType() != null && castOther.getEntType() != null && this
						.getEntType().equals(castOther.getEntType())))
				&& ((this.getEntPcode() == castOther.getEntPcode()) || (this
						.getEntPcode() != null
						&& castOther.getEntPcode() != null && this
						.getEntPcode().equals(castOther.getEntPcode())))
				&& ((this.getEntEmail() == castOther.getEntEmail()) || (this
						.getEntEmail() != null
						&& castOther.getEntEmail() != null && this
						.getEntEmail().equals(castOther.getEntEmail())))
				&& ((this.getEntContactMan() == castOther.getEntContactMan()) || (this
						.getEntContactMan() != null
						&& castOther.getEntContactMan() != null && this
						.getEntContactMan()
						.equals(castOther.getEntContactMan())))
				&& ((this.getEntContactPhone() == castOther
						.getEntContactPhone()) || (this.getEntContactPhone() != null
						&& castOther.getEntContactPhone() != null && this
						.getEntContactPhone().equals(
								castOther.getEntContactPhone())))
				&& ((this.getEntContactAddr() == castOther.getEntContactAddr()) || (this
						.getEntContactAddr() != null
						&& castOther.getEntContactAddr() != null && this
						.getEntContactAddr().equals(
								castOther.getEntContactAddr())))
				&& (this.getEntTypeEconomyNo() == castOther
						.getEntTypeEconomyNo())
				&& ((this.getEntTypeEconomyName() == castOther
						.getEntTypeEconomyName()) || (this
						.getEntTypeEconomyName() != null
						&& castOther.getEntTypeEconomyName() != null && this
						.getEntTypeEconomyName().equals(
								castOther.getEntTypeEconomyName())))
				&& (this.getEntTypeTradeNo() == castOther.getEntTypeTradeNo())
				&& ((this.getEntTypeTradeName() == castOther
						.getEntTypeTradeName()) || (this.getEntTypeTradeName() != null
						&& castOther.getEntTypeTradeName() != null && this
						.getEntTypeTradeName().equals(
								castOther.getEntTypeTradeName())))
				&& (this.getEntAddrDisNo() == castOther.getEntAddrDisNo())
				&& ((this.getCommunityAddr() == castOther.getCommunityAddr()) || (this
						.getCommunityAddr() != null
						&& castOther.getCommunityAddr() != null && this
						.getCommunityAddr()
						.equals(castOther.getCommunityAddr())))
				&& ((this.getEntSercurityNum() == castOther
						.getEntSercurityNum()) || (this.getEntSercurityNum() != null
						&& castOther.getEntSercurityNum() != null && this
						.getEntSercurityNum().equals(
								castOther.getEntSercurityNum())))
				&& ((this.getEntScaleNo() == castOther.getEntScaleNo()) || (this
						.getEntScaleNo() != null
						&& castOther.getEntScaleNo() != null && this
						.getEntScaleNo().equals(castOther.getEntScaleNo())))
				&& ((this.getScaleName() == castOther.getScaleName()) || (this
						.getScaleName() != null
						&& castOther.getScaleName() != null && this
						.getScaleName().equals(castOther.getScaleName())))
				&& ((this.getEntOCode() == castOther.getEntOCode()) || (this
						.getEntOCode() != null
						&& castOther.getEntOCode() != null && this
						.getEntOCode().equals(castOther.getEntOCode())))
				&& ((this.getEntCertUrlSer() == castOther.getEntCertUrlSer()) || (this
						.getEntCertUrlSer() != null
						&& castOther.getEntCertUrlSer() != null && this
						.getEntCertUrlSer()
						.equals(castOther.getEntCertUrlSer())))
				&& ((this.getEntCertUrlO() == castOther.getEntCertUrlO()) || (this
						.getEntCertUrlO() != null
						&& castOther.getEntCertUrlO() != null && this
						.getEntCertUrlO().equals(castOther.getEntCertUrlO())))
				&& ((this.getEntCertUrlLicence() == castOther
						.getEntCertUrlLicence()) || (this
						.getEntCertUrlLicence() != null
						&& castOther.getEntCertUrlLicence() != null && this
						.getEntCertUrlLicence().equals(
								castOther.getEntCertUrlLicence())))
				&& ((this.getEntContent() == castOther.getEntContent()) || (this
						.getEntContent() != null
						&& castOther.getEntContent() != null && this
						.getEntContent().equals(castOther.getEntContent())))
				&& ((this.getReserved01() == castOther.getReserved01()) || (this
						.getReserved01() != null
						&& castOther.getReserved01() != null && this
						.getReserved01().equals(castOther.getReserved01())))
				&& ((this.getReserved02() == castOther.getReserved02()) || (this
						.getReserved02() != null
						&& castOther.getReserved02() != null && this
						.getReserved02().equals(castOther.getReserved02())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEntNo();
		result = 37 * result
				+ (getEntName() == null ? 0 : this.getEntName().hashCode());
		result = 37 * result
				+ (getEntUid() == null ? 0 : this.getEntUid().hashCode());
		result = 37 * result
				+ (getEntType() == null ? 0 : this.getEntType().hashCode());
		result = 37 * result
				+ (getEntPcode() == null ? 0 : this.getEntPcode().hashCode());
		result = 37 * result
				+ (getEntEmail() == null ? 0 : this.getEntEmail().hashCode());
		result = 37
				* result
				+ (getEntContactMan() == null ? 0 : this.getEntContactMan()
						.hashCode());
		result = 37
				* result
				+ (getEntContactPhone() == null ? 0 : this.getEntContactPhone()
						.hashCode());
		result = 37
				* result
				+ (getEntContactAddr() == null ? 0 : this.getEntContactAddr()
						.hashCode());
		result = 37 * result + this.getEntTypeEconomyNo();
		result = 37
				* result
				+ (getEntTypeEconomyName() == null ? 0 : this
						.getEntTypeEconomyName().hashCode());
		result = 37 * result + this.getEntTypeTradeNo();
		result = 37
				* result
				+ (getEntTypeTradeName() == null ? 0 : this
						.getEntTypeTradeName().hashCode());
		result = 37 * result + this.getEntAddrDisNo();
		result = 37
				* result
				+ (getCommunityAddr() == null ? 0 : this.getCommunityAddr()
						.hashCode());
		result = 37
				* result
				+ (getEntSercurityNum() == null ? 0 : this.getEntSercurityNum()
						.hashCode());
		result = 37
				* result
				+ (getEntScaleNo() == null ? 0 : this.getEntScaleNo()
						.hashCode());
		result = 37 * result
				+ (getScaleName() == null ? 0 : this.getScaleName().hashCode());
		result = 37 * result
				+ (getEntOCode() == null ? 0 : this.getEntOCode().hashCode());
		result = 37
				* result
				+ (getEntCertUrlSer() == null ? 0 : this.getEntCertUrlSer()
						.hashCode());
		result = 37
				* result
				+ (getEntCertUrlO() == null ? 0 : this.getEntCertUrlO()
						.hashCode());
		result = 37
				* result
				+ (getEntCertUrlLicence() == null ? 0 : this
						.getEntCertUrlLicence().hashCode());
		result = 37
				* result
				+ (getEntContent() == null ? 0 : this.getEntContent()
						.hashCode());
		result = 37
				* result
				+ (getReserved01() == null ? 0 : this.getReserved01()
						.hashCode());
		result = 37
				* result
				+ (getReserved02() == null ? 0 : this.getReserved02()
						.hashCode());
		return result;
	}

}
