package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepEntFavouriteId generated by hbm2java
 */
public class RepEntFavouriteId implements java.io.Serializable {

	private int userNo;
	private int entNo;

	public RepEntFavouriteId() {
	}

	public RepEntFavouriteId(int userNo, int entNo) {
		this.userNo = userNo;
		this.entNo = entNo;
	}

	public int getUserNo() {
		return this.userNo;
	}

	public void setUserNo(int userNo) {
		this.userNo = userNo;
	}

	public int getEntNo() {
		return this.entNo;
	}

	public void setEntNo(int entNo) {
		this.entNo = entNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepEntFavouriteId))
			return false;
		RepEntFavouriteId castOther = (RepEntFavouriteId) other;

		return (this.getUserNo() == castOther.getUserNo())
				&& (this.getEntNo() == castOther.getEntNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserNo();
		result = 37 * result + this.getEntNo();
		return result;
	}

}
