package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RepEntJobUserViewId generated by hbm2java
 */
public class RepEntJobUserViewId implements java.io.Serializable {

	private int jobNo;
	private String jobName;
	private String jobAddrPosName;
	private int state;
	private String stateName;
	private Date submittime;
	private Date auditiontime;
	private Date hiretime;
	private Date trytime;
	private Date dismisstime;
	private Date membertime;
	private Date contracttime;
	private String memo;
	private String reserved01;
	private int userNo;
	private String userName;
	private String userSex;
	private Integer userAge;
	private String userPhone;
	private String userCert;
	private String userEmail;
	private String educationDictName;
	private Integer entNo;
	private String entName;

	public RepEntJobUserViewId() {
	}

	public RepEntJobUserViewId(int jobNo, int state, Date submittime, int userNo) {
		this.jobNo = jobNo;
		this.state = state;
		this.submittime = submittime;
		this.userNo = userNo;
	}

	public RepEntJobUserViewId(int jobNo, String jobName,
			String jobAddrPosName, int state, String stateName,
			Date submittime, Date auditiontime, Date hiretime, Date trytime,
			Date dismisstime, Date membertime, Date contracttime, String memo,
			String reserved01, int userNo, String userName, String userSex,
			Integer userAge, String userPhone, String userCert,
			String userEmail, String educationDictName, Integer entNo,
			String entName) {
		this.jobNo = jobNo;
		this.jobName = jobName;
		this.jobAddrPosName = jobAddrPosName;
		this.state = state;
		this.stateName = stateName;
		this.submittime = submittime;
		this.auditiontime = auditiontime;
		this.hiretime = hiretime;
		this.trytime = trytime;
		this.dismisstime = dismisstime;
		this.membertime = membertime;
		this.contracttime = contracttime;
		this.memo = memo;
		this.reserved01 = reserved01;
		this.userNo = userNo;
		this.userName = userName;
		this.userSex = userSex;
		this.userAge = userAge;
		this.userPhone = userPhone;
		this.userCert = userCert;
		this.userEmail = userEmail;
		this.educationDictName = educationDictName;
		this.entNo = entNo;
		this.entName = entName;
	}

	public int getJobNo() {
		return this.jobNo;
	}

	public void setJobNo(int jobNo) {
		this.jobNo = jobNo;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getJobAddrPosName() {
		return this.jobAddrPosName;
	}

	public void setJobAddrPosName(String jobAddrPosName) {
		this.jobAddrPosName = jobAddrPosName;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	public Date getSubmittime() {
		return this.submittime;
	}

	public void setSubmittime(Date submittime) {
		this.submittime = submittime;
	}

	public Date getAuditiontime() {
		return this.auditiontime;
	}

	public void setAuditiontime(Date auditiontime) {
		this.auditiontime = auditiontime;
	}

	public Date getHiretime() {
		return this.hiretime;
	}

	public void setHiretime(Date hiretime) {
		this.hiretime = hiretime;
	}

	public Date getTrytime() {
		return this.trytime;
	}

	public void setTrytime(Date trytime) {
		this.trytime = trytime;
	}

	public Date getDismisstime() {
		return this.dismisstime;
	}

	public void setDismisstime(Date dismisstime) {
		this.dismisstime = dismisstime;
	}

	public Date getMembertime() {
		return this.membertime;
	}

	public void setMembertime(Date membertime) {
		this.membertime = membertime;
	}

	public Date getContracttime() {
		return this.contracttime;
	}

	public void setContracttime(Date contracttime) {
		this.contracttime = contracttime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public int getUserNo() {
		return this.userNo;
	}

	public void setUserNo(int userNo) {
		this.userNo = userNo;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	public Integer getUserAge() {
		return this.userAge;
	}

	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserCert() {
		return this.userCert;
	}

	public void setUserCert(String userCert) {
		this.userCert = userCert;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getEducationDictName() {
		return this.educationDictName;
	}

	public void setEducationDictName(String educationDictName) {
		this.educationDictName = educationDictName;
	}

	public Integer getEntNo() {
		return this.entNo;
	}

	public void setEntNo(Integer entNo) {
		this.entNo = entNo;
	}

	public String getEntName() {
		return this.entName;
	}

	public void setEntName(String entName) {
		this.entName = entName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepEntJobUserViewId))
			return false;
		RepEntJobUserViewId castOther = (RepEntJobUserViewId) other;

		return (this.getJobNo() == castOther.getJobNo())
				&& ((this.getJobName() == castOther.getJobName()) || (this
						.getJobName() != null && castOther.getJobName() != null && this
						.getJobName().equals(castOther.getJobName())))
				&& ((this.getJobAddrPosName() == castOther.getJobAddrPosName()) || (this
						.getJobAddrPosName() != null
						&& castOther.getJobAddrPosName() != null && this
						.getJobAddrPosName().equals(
								castOther.getJobAddrPosName())))
				&& (this.getState() == castOther.getState())
				&& ((this.getStateName() == castOther.getStateName()) || (this
						.getStateName() != null
						&& castOther.getStateName() != null && this
						.getStateName().equals(castOther.getStateName())))
				&& ((this.getSubmittime() == castOther.getSubmittime()) || (this
						.getSubmittime() != null
						&& castOther.getSubmittime() != null && this
						.getSubmittime().equals(castOther.getSubmittime())))
				&& ((this.getAuditiontime() == castOther.getAuditiontime()) || (this
						.getAuditiontime() != null
						&& castOther.getAuditiontime() != null && this
						.getAuditiontime().equals(castOther.getAuditiontime())))
				&& ((this.getHiretime() == castOther.getHiretime()) || (this
						.getHiretime() != null
						&& castOther.getHiretime() != null && this
						.getHiretime().equals(castOther.getHiretime())))
				&& ((this.getTrytime() == castOther.getTrytime()) || (this
						.getTrytime() != null && castOther.getTrytime() != null && this
						.getTrytime().equals(castOther.getTrytime())))
				&& ((this.getDismisstime() == castOther.getDismisstime()) || (this
						.getDismisstime() != null
						&& castOther.getDismisstime() != null && this
						.getDismisstime().equals(castOther.getDismisstime())))
				&& ((this.getMembertime() == castOther.getMembertime()) || (this
						.getMembertime() != null
						&& castOther.getMembertime() != null && this
						.getMembertime().equals(castOther.getMembertime())))
				&& ((this.getContracttime() == castOther.getContracttime()) || (this
						.getContracttime() != null
						&& castOther.getContracttime() != null && this
						.getContracttime().equals(castOther.getContracttime())))
				&& ((this.getMemo() == castOther.getMemo()) || (this.getMemo() != null
						&& castOther.getMemo() != null && this.getMemo()
						.equals(castOther.getMemo())))
				&& ((this.getReserved01() == castOther.getReserved01()) || (this
						.getReserved01() != null
						&& castOther.getReserved01() != null && this
						.getReserved01().equals(castOther.getReserved01())))
				&& (this.getUserNo() == castOther.getUserNo())
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserSex() == castOther.getUserSex()) || (this
						.getUserSex() != null && castOther.getUserSex() != null && this
						.getUserSex().equals(castOther.getUserSex())))
				&& ((this.getUserAge() == castOther.getUserAge()) || (this
						.getUserAge() != null && castOther.getUserAge() != null && this
						.getUserAge().equals(castOther.getUserAge())))
				&& ((this.getUserPhone() == castOther.getUserPhone()) || (this
						.getUserPhone() != null
						&& castOther.getUserPhone() != null && this
						.getUserPhone().equals(castOther.getUserPhone())))
				&& ((this.getUserCert() == castOther.getUserCert()) || (this
						.getUserCert() != null
						&& castOther.getUserCert() != null && this
						.getUserCert().equals(castOther.getUserCert())))
				&& ((this.getUserEmail() == castOther.getUserEmail()) || (this
						.getUserEmail() != null
						&& castOther.getUserEmail() != null && this
						.getUserEmail().equals(castOther.getUserEmail())))
				&& ((this.getEducationDictName() == castOther
						.getEducationDictName()) || (this
						.getEducationDictName() != null
						&& castOther.getEducationDictName() != null && this
						.getEducationDictName().equals(
								castOther.getEducationDictName())))
				&& ((this.getEntNo() == castOther.getEntNo()) || (this
						.getEntNo() != null && castOther.getEntNo() != null && this
						.getEntNo().equals(castOther.getEntNo())))
				&& ((this.getEntName() == castOther.getEntName()) || (this
						.getEntName() != null && castOther.getEntName() != null && this
						.getEntName().equals(castOther.getEntName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getJobNo();
		result = 37 * result
				+ (getJobName() == null ? 0 : this.getJobName().hashCode());
		result = 37
				* result
				+ (getJobAddrPosName() == null ? 0 : this.getJobAddrPosName()
						.hashCode());
		result = 37 * result + this.getState();
		result = 37 * result
				+ (getStateName() == null ? 0 : this.getStateName().hashCode());
		result = 37
				* result
				+ (getSubmittime() == null ? 0 : this.getSubmittime()
						.hashCode());
		result = 37
				* result
				+ (getAuditiontime() == null ? 0 : this.getAuditiontime()
						.hashCode());
		result = 37 * result
				+ (getHiretime() == null ? 0 : this.getHiretime().hashCode());
		result = 37 * result
				+ (getTrytime() == null ? 0 : this.getTrytime().hashCode());
		result = 37
				* result
				+ (getDismisstime() == null ? 0 : this.getDismisstime()
						.hashCode());
		result = 37
				* result
				+ (getMembertime() == null ? 0 : this.getMembertime()
						.hashCode());
		result = 37
				* result
				+ (getContracttime() == null ? 0 : this.getContracttime()
						.hashCode());
		result = 37 * result
				+ (getMemo() == null ? 0 : this.getMemo().hashCode());
		result = 37
				* result
				+ (getReserved01() == null ? 0 : this.getReserved01()
						.hashCode());
		result = 37 * result + this.getUserNo();
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getUserSex() == null ? 0 : this.getUserSex().hashCode());
		result = 37 * result
				+ (getUserAge() == null ? 0 : this.getUserAge().hashCode());
		result = 37 * result
				+ (getUserPhone() == null ? 0 : this.getUserPhone().hashCode());
		result = 37 * result
				+ (getUserCert() == null ? 0 : this.getUserCert().hashCode());
		result = 37 * result
				+ (getUserEmail() == null ? 0 : this.getUserEmail().hashCode());
		result = 37
				* result
				+ (getEducationDictName() == null ? 0 : this
						.getEducationDictName().hashCode());
		result = 37 * result
				+ (getEntNo() == null ? 0 : this.getEntNo().hashCode());
		result = 37 * result
				+ (getEntName() == null ? 0 : this.getEntName().hashCode());
		return result;
	}

}
