package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RepEntTrainUser generated by hbm2java
 */
public class RepEntTrainUser implements java.io.Serializable {

	private Integer trainUserNo;
	private int userNo;
	private int newsNo;
	private int state;
	private Date submittime;
	private String memo;
	private String reserved01;

	public RepEntTrainUser() {
	}

	public RepEntTrainUser(int userNo, int newsNo, int state, Date submittime) {
		this.userNo = userNo;
		this.newsNo = newsNo;
		this.state = state;
		this.submittime = submittime;
	}

	public RepEntTrainUser(int userNo, int newsNo, int state, Date submittime,
			String memo, String reserved01) {
		this.userNo = userNo;
		this.newsNo = newsNo;
		this.state = state;
		this.submittime = submittime;
		this.memo = memo;
		this.reserved01 = reserved01;
	}

	public Integer getTrainUserNo() {
		return this.trainUserNo;
	}

	public void setTrainUserNo(Integer trainUserNo) {
		this.trainUserNo = trainUserNo;
	}

	public int getUserNo() {
		return this.userNo;
	}

	public void setUserNo(int userNo) {
		this.userNo = userNo;
	}

	public int getNewsNo() {
		return this.newsNo;
	}

	public void setNewsNo(int newsNo) {
		this.newsNo = newsNo;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getSubmittime() {
		return this.submittime;
	}

	public void setSubmittime(Date submittime) {
		this.submittime = submittime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

}
