package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepEntFavouriteView generated by hbm2java
 */
public class RepEntFavouriteView implements java.io.Serializable {

	private RepEntFavouriteViewId id;

	public RepEntFavouriteView() {
	}

	public RepEntFavouriteView(RepEntFavouriteViewId id) {
		this.id = id;
	}

	public RepEntFavouriteViewId getId() {
		return this.id;
	}

	public void setId(RepEntFavouriteViewId id) {
		this.id = id;
	}

}
