package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RepTrainUserViewId generated by hbm2java
 */
public class RepTrainUserViewId implements java.io.Serializable {

	private int trainUserNo;
	private int userNo;
	private int newsNo;
	private String newsTitle;
	private int state;
	private Date submittime;
	private String memo;
	private String reserved01;
	private String userName;
	private String userSex;
	private String userPhone;
	private String userEmail;
	private Date newsTrainEndtime;

	public RepTrainUserViewId() {
	}

	public RepTrainUserViewId(int trainUserNo, int userNo, int newsNo,
			int state, Date submittime, String userEmail) {
		this.trainUserNo = trainUserNo;
		this.userNo = userNo;
		this.newsNo = newsNo;
		this.state = state;
		this.submittime = submittime;
		this.userEmail = userEmail;
	}

	public RepTrainUserViewId(int trainUserNo, int userNo, int newsNo,
			String newsTitle, int state, Date submittime, String memo,
			String reserved01, String userName, String userSex,
			String userPhone, String userEmail, Date newsTrainEndtime) {
		this.trainUserNo = trainUserNo;
		this.userNo = userNo;
		this.newsNo = newsNo;
		this.newsTitle = newsTitle;
		this.state = state;
		this.submittime = submittime;
		this.memo = memo;
		this.reserved01 = reserved01;
		this.userName = userName;
		this.userSex = userSex;
		this.userPhone = userPhone;
		this.userEmail = userEmail;
		this.newsTrainEndtime = newsTrainEndtime;
	}

	public int getTrainUserNo() {
		return this.trainUserNo;
	}

	public void setTrainUserNo(int trainUserNo) {
		this.trainUserNo = trainUserNo;
	}

	public int getUserNo() {
		return this.userNo;
	}

	public void setUserNo(int userNo) {
		this.userNo = userNo;
	}

	public int getNewsNo() {
		return this.newsNo;
	}

	public void setNewsNo(int newsNo) {
		this.newsNo = newsNo;
	}

	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getSubmittime() {
		return this.submittime;
	}

	public void setSubmittime(Date submittime) {
		this.submittime = submittime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public Date getNewsTrainEndtime() {
		return this.newsTrainEndtime;
	}

	public void setNewsTrainEndtime(Date newsTrainEndtime) {
		this.newsTrainEndtime = newsTrainEndtime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepTrainUserViewId))
			return false;
		RepTrainUserViewId castOther = (RepTrainUserViewId) other;

		return (this.getTrainUserNo() == castOther.getTrainUserNo())
				&& (this.getUserNo() == castOther.getUserNo())
				&& (this.getNewsNo() == castOther.getNewsNo())
				&& ((this.getNewsTitle() == castOther.getNewsTitle()) || (this
						.getNewsTitle() != null
						&& castOther.getNewsTitle() != null && this
						.getNewsTitle().equals(castOther.getNewsTitle())))
				&& (this.getState() == castOther.getState())
				&& ((this.getSubmittime() == castOther.getSubmittime()) || (this
						.getSubmittime() != null
						&& castOther.getSubmittime() != null && this
						.getSubmittime().equals(castOther.getSubmittime())))
				&& ((this.getMemo() == castOther.getMemo()) || (this.getMemo() != null
						&& castOther.getMemo() != null && this.getMemo()
						.equals(castOther.getMemo())))
				&& ((this.getReserved01() == castOther.getReserved01()) || (this
						.getReserved01() != null
						&& castOther.getReserved01() != null && this
						.getReserved01().equals(castOther.getReserved01())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserSex() == castOther.getUserSex()) || (this
						.getUserSex() != null && castOther.getUserSex() != null && this
						.getUserSex().equals(castOther.getUserSex())))
				&& ((this.getUserPhone() == castOther.getUserPhone()) || (this
						.getUserPhone() != null
						&& castOther.getUserPhone() != null && this
						.getUserPhone().equals(castOther.getUserPhone())))
				&& ((this.getUserEmail() == castOther.getUserEmail()) || (this
						.getUserEmail() != null
						&& castOther.getUserEmail() != null && this
						.getUserEmail().equals(castOther.getUserEmail())))
				&& ((this.getNewsTrainEndtime() == castOther
						.getNewsTrainEndtime()) || (this.getNewsTrainEndtime() != null
						&& castOther.getNewsTrainEndtime() != null && this
						.getNewsTrainEndtime().equals(
								castOther.getNewsTrainEndtime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTrainUserNo();
		result = 37 * result + this.getUserNo();
		result = 37 * result + this.getNewsNo();
		result = 37 * result
				+ (getNewsTitle() == null ? 0 : this.getNewsTitle().hashCode());
		result = 37 * result + this.getState();
		result = 37
				* result
				+ (getSubmittime() == null ? 0 : this.getSubmittime()
						.hashCode());
		result = 37 * result
				+ (getMemo() == null ? 0 : this.getMemo().hashCode());
		result = 37
				* result
				+ (getReserved01() == null ? 0 : this.getReserved01()
						.hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getUserSex() == null ? 0 : this.getUserSex().hashCode());
		result = 37 * result
				+ (getUserPhone() == null ? 0 : this.getUserPhone().hashCode());
		result = 37 * result
				+ (getUserEmail() == null ? 0 : this.getUserEmail().hashCode());
		result = 37
				* result
				+ (getNewsTrainEndtime() == null ? 0 : this
						.getNewsTrainEndtime().hashCode());
		return result;
	}

}
