package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepTrainUserView generated by hbm2java
 */
public class RepTrainUserView implements java.io.Serializable {

	private RepTrainUserViewId id;

	public RepTrainUserView() {
	}

	public RepTrainUserView(RepTrainUserViewId id) {
		this.id = id;
	}

	public RepTrainUserViewId getId() {
		return this.id;
	}

	public void setId(RepTrainUserViewId id) {
		this.id = id;
	}

}
