package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepUserAble generated by hbm2java
 */
public class RepUserAble implements java.io.Serializable {

	private Integer gid;
	private int userno;
	private String language;
	private String listen;
	private String write;

	public RepUserAble() {
	}

	public RepUserAble(int userno) {
		this.userno = userno;
	}

	public RepUserAble(int userno, String language, String listen, String write) {
		this.userno = userno;
		this.language = language;
		this.listen = listen;
		this.write = write;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public int getUserno() {
		return this.userno;
	}

	public void setUserno(int userno) {
		this.userno = userno;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getListen() {
		return this.listen;
	}

	public void setListen(String listen) {
		this.listen = listen;
	}

	public String getWrite() {
		return this.write;
	}

	public void setWrite(String write) {
		this.write = write;
	}

}
