package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepUserInfoView generated by hbm2java
 */
public class RepUserInfoView implements java.io.Serializable {

	private RepUserInfoViewId id;

	public RepUserInfoView() {
	}

	public RepUserInfoView(RepUserInfoViewId id) {
		this.id = id;
	}

	public RepUserInfoViewId getId() {
		return this.id;
	}

	public void setId(RepUserInfoViewId id) {
		this.id = id;
	}

}
