package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RepUserTrainExp generated by hbm2java
 */
public class RepUserTrainExp implements java.io.Serializable {

	private Integer gid;
	private int userno;
	private Date traintime;
	private String trainorgan;
	private String traincourse;
	private String certificate;
	private String describe;

	public RepUserTrainExp() {
	}

	public RepUserTrainExp(int userno) {
		this.userno = userno;
	}

	public RepUserTrainExp(int userno, Date traintime, String trainorgan,
			String traincourse, String certificate, String describe) {
		this.userno = userno;
		this.traintime = traintime;
		this.trainorgan = trainorgan;
		this.traincourse = traincourse;
		this.certificate = certificate;
		this.describe = describe;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public int getUserno() {
		return this.userno;
	}

	public void setUserno(int userno) {
		this.userno = userno;
	}

	public Date getTraintime() {
		return this.traintime;
	}

	public void setTraintime(Date traintime) {
		this.traintime = traintime;
	}

	public String getTrainorgan() {
		return this.trainorgan;
	}

	public void setTrainorgan(String trainorgan) {
		this.trainorgan = trainorgan;
	}

	public String getTraincourse() {
		return this.traincourse;
	}

	public void setTraincourse(String traincourse) {
		this.traincourse = traincourse;
	}

	public String getCertificate() {
		return this.certificate;
	}

	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

}
