package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepUserResumeView generated by hbm2java
 */
public class RepUserResumeView implements java.io.Serializable {

	private RepUserResumeViewId id;

	public RepUserResumeView() {
	}

	public RepUserResumeView(RepUserResumeViewId id) {
		this.id = id;
	}

	public RepUserResumeViewId getId() {
		return this.id;
	}

	public void setId(RepUserResumeViewId id) {
		this.id = id;
	}

}
