package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepEntJobUserView generated by hbm2java
 */
public class RepEntJobUserView implements java.io.Serializable {

	private RepEntJobUserViewId id;

	public RepEntJobUserView() {
	}

	public RepEntJobUserView(RepEntJobUserViewId id) {
		this.id = id;
	}

	public RepEntJobUserViewId getId() {
		return this.id;
	}

	public void setId(RepEntJobUserViewId id) {
		this.id = id;
	}

}
