package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepAdminUserEducationDict generated by hbm2java
 */
public class RepAdminUserEducationDict implements java.io.Serializable {

	private int educationDictNo;
	private String educationDictName;
	private Integer educationDictType;
	private Integer educationDictLevel;
	private String reserved01;

	public RepAdminUserEducationDict() {
	}

	public RepAdminUserEducationDict(int educationDictNo,
			String educationDictName) {
		this.educationDictNo = educationDictNo;
		this.educationDictName = educationDictName;
	}

	public RepAdminUserEducationDict(int educationDictNo,
			String educationDictName, Integer educationDictType,
			Integer educationDictLevel, String reserved01) {
		this.educationDictNo = educationDictNo;
		this.educationDictName = educationDictName;
		this.educationDictType = educationDictType;
		this.educationDictLevel = educationDictLevel;
		this.reserved01 = reserved01;
	}

	public int getEducationDictNo() {
		return this.educationDictNo;
	}

	public void setEducationDictNo(int educationDictNo) {
		this.educationDictNo = educationDictNo;
	}

	public String getEducationDictName() {
		return this.educationDictName;
	}

	public void setEducationDictName(String educationDictName) {
		this.educationDictName = educationDictName;
	}

	public Integer getEducationDictType() {
		return this.educationDictType;
	}

	public void setEducationDictType(Integer educationDictType) {
		this.educationDictType = educationDictType;
	}

	public Integer getEducationDictLevel() {
		return this.educationDictLevel;
	}

	public void setEducationDictLevel(Integer educationDictLevel) {
		this.educationDictLevel = educationDictLevel;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

}
