package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepAdminSys generated by hbm2java
 */
public class RepAdminSys implements java.io.Serializable {

	private int sysNo;
	private String sysName;
	private String sysValue;
	private Integer sysState;

	public RepAdminSys() {
	}

	public RepAdminSys(int sysNo) {
		this.sysNo = sysNo;
	}

	public RepAdminSys(int sysNo, String sysName, String sysValue,
			Integer sysState) {
		this.sysNo = sysNo;
		this.sysName = sysName;
		this.sysValue = sysValue;
		this.sysState = sysState;
	}

	public int getSysNo() {
		return this.sysNo;
	}

	public void setSysNo(int sysNo) {
		this.sysNo = sysNo;
	}

	public String getSysName() {
		return this.sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	public String getSysValue() {
		return this.sysValue;
	}

	public void setSysValue(String sysValue) {
		this.sysValue = sysValue;
	}

	public Integer getSysState() {
		return this.sysState;
	}

	public void setSysState(Integer sysState) {
		this.sysState = sysState;
	}

}
