package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepEntInfo generated by hbm2java
 */
public class RepEntInfo implements java.io.Serializable {

	private Integer entNo;
	private String entName;
	private String entUid;
	private String entPwd;
	private String entEmail;
	private String entType;
	private Integer entPcode;
	private String entContactMan;
	private String entContactPhone;
	private String entContactAddr;
	private int entTypeEconomy;
	private int entTypeTrade;
	private int entAddrDisNo;
	private String entScaleNo;
	private String entSercurityNum;
	private String entOCode;
	private String entCertUrlSer;
	private String entCertUrlO;
	private String entCertUrlLicence;
	private String entContent;
	private String reserved01;
	private Integer reserved02;
	private String reserved03;

	public RepEntInfo() {
	}

	public RepEntInfo(String entName, String entUid, String entPwd,
			String entEmail, int entTypeEconomy, int entTypeTrade,
			int entAddrDisNo) {
		this.entName = entName;
		this.entUid = entUid;
		this.entPwd = entPwd;
		this.entEmail = entEmail;
		this.entTypeEconomy = entTypeEconomy;
		this.entTypeTrade = entTypeTrade;
		this.entAddrDisNo = entAddrDisNo;
	}

	public RepEntInfo(String entName, String entUid, String entPwd,
			String entEmail, String entType, Integer entPcode,
			String entContactMan, String entContactPhone,
			String entContactAddr, int entTypeEconomy, int entTypeTrade,
			int entAddrDisNo, String entScaleNo, String entSercurityNum,
			String entOCode, String entCertUrlSer, String entCertUrlO,
			String entCertUrlLicence, String entContent, String reserved01,
			Integer reserved02, String reserved03) {
		this.entName = entName;
		this.entUid = entUid;
		this.entPwd = entPwd;
		this.entEmail = entEmail;
		this.entType = entType;
		this.entPcode = entPcode;
		this.entContactMan = entContactMan;
		this.entContactPhone = entContactPhone;
		this.entContactAddr = entContactAddr;
		this.entTypeEconomy = entTypeEconomy;
		this.entTypeTrade = entTypeTrade;
		this.entAddrDisNo = entAddrDisNo;
		this.entScaleNo = entScaleNo;
		this.entSercurityNum = entSercurityNum;
		this.entOCode = entOCode;
		this.entCertUrlSer = entCertUrlSer;
		this.entCertUrlO = entCertUrlO;
		this.entCertUrlLicence = entCertUrlLicence;
		this.entContent = entContent;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
	}

	public Integer getEntNo() {
		return this.entNo;
	}

	public void setEntNo(Integer entNo) {
		this.entNo = entNo;
	}

	public String getEntName() {
		return this.entName;
	}

	public void setEntName(String entName) {
		this.entName = entName;
	}

	public String getEntUid() {
		return this.entUid;
	}

	public void setEntUid(String entUid) {
		this.entUid = entUid;
	}

	public String getEntPwd() {
		return this.entPwd;
	}

	public void setEntPwd(String entPwd) {
		this.entPwd = entPwd;
	}

	public String getEntEmail() {
		return this.entEmail;
	}

	public void setEntEmail(String entEmail) {
		this.entEmail = entEmail;
	}

	public String getEntType() {
		return this.entType;
	}

	public void setEntType(String entType) {
		this.entType = entType;
	}

	public Integer getEntPcode() {
		return this.entPcode;
	}

	public void setEntPcode(Integer entPcode) {
		this.entPcode = entPcode;
	}

	public String getEntContactMan() {
		return this.entContactMan;
	}

	public void setEntContactMan(String entContactMan) {
		this.entContactMan = entContactMan;
	}

	public String getEntContactPhone() {
		return this.entContactPhone;
	}

	public void setEntContactPhone(String entContactPhone) {
		this.entContactPhone = entContactPhone;
	}

	public String getEntContactAddr() {
		return this.entContactAddr;
	}

	public void setEntContactAddr(String entContactAddr) {
		this.entContactAddr = entContactAddr;
	}

	public int getEntTypeEconomy() {
		return this.entTypeEconomy;
	}

	public void setEntTypeEconomy(int entTypeEconomy) {
		this.entTypeEconomy = entTypeEconomy;
	}

	public int getEntTypeTrade() {
		return this.entTypeTrade;
	}

	public void setEntTypeTrade(int entTypeTrade) {
		this.entTypeTrade = entTypeTrade;
	}

	public int getEntAddrDisNo() {
		return this.entAddrDisNo;
	}

	public void setEntAddrDisNo(int entAddrDisNo) {
		this.entAddrDisNo = entAddrDisNo;
	}

	public String getEntScaleNo() {
		return this.entScaleNo;
	}

	public void setEntScaleNo(String entScaleNo) {
		this.entScaleNo = entScaleNo;
	}

	public String getEntSercurityNum() {
		return this.entSercurityNum;
	}

	public void setEntSercurityNum(String entSercurityNum) {
		this.entSercurityNum = entSercurityNum;
	}

	public String getEntOCode() {
		return this.entOCode;
	}

	public void setEntOCode(String entOCode) {
		this.entOCode = entOCode;
	}

	public String getEntCertUrlSer() {
		return this.entCertUrlSer;
	}

	public void setEntCertUrlSer(String entCertUrlSer) {
		this.entCertUrlSer = entCertUrlSer;
	}

	public String getEntCertUrlO() {
		return this.entCertUrlO;
	}

	public void setEntCertUrlO(String entCertUrlO) {
		this.entCertUrlO = entCertUrlO;
	}

	public String getEntCertUrlLicence() {
		return this.entCertUrlLicence;
	}

	public void setEntCertUrlLicence(String entCertUrlLicence) {
		this.entCertUrlLicence = entCertUrlLicence;
	}

	public String getEntContent() {
		return this.entContent;
	}

	public void setEntContent(String entContent) {
		this.entContent = entContent;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public Integer getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(Integer reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

}
