package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepUserProgram generated by hbm2java
 */
public class RepUserProgram implements java.io.Serializable {

	private Integer gid;
	private int userno;
	private String pname;
	private String ptime;
	private String company;
	private String proJobname;
	private String proDescribe;
	private String pduty;
	private String jobgain;

	public RepUserProgram() {
	}

	public RepUserProgram(int userno) {
		this.userno = userno;
	}

	public RepUserProgram(int userno, String pname, String ptime,
			String company, String proJobname, String proDescribe,
			String pduty, String jobgain) {
		this.userno = userno;
		this.pname = pname;
		this.ptime = ptime;
		this.company = company;
		this.proJobname = proJobname;
		this.proDescribe = proDescribe;
		this.pduty = pduty;
		this.jobgain = jobgain;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public int getUserno() {
		return this.userno;
	}

	public void setUserno(int userno) {
		this.userno = userno;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPtime() {
		return this.ptime;
	}

	public void setPtime(String ptime) {
		this.ptime = ptime;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getProJobname() {
		return this.proJobname;
	}

	public void setProJobname(String proJobname) {
		this.proJobname = proJobname;
	}

	public String getProDescribe() {
		return this.proDescribe;
	}

	public void setProDescribe(String proDescribe) {
		this.proDescribe = proDescribe;
	}

	public String getPduty() {
		return this.pduty;
	}

	public void setPduty(String pduty) {
		this.pduty = pduty;
	}

	public String getJobgain() {
		return this.jobgain;
	}

	public void setJobgain(String jobgain) {
		this.jobgain = jobgain;
	}

}
