package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepAdminEntEconomyDict generated by hbm2java
 */
public class RepAdminEntEconomyDict implements java.io.Serializable {

	private int economyNo;
	private String economyName;
	private String reserved01;

	public RepAdminEntEconomyDict() {
	}

	public RepAdminEntEconomyDict(int economyNo) {
		this.economyNo = economyNo;
	}

	public RepAdminEntEconomyDict(int economyNo, String economyName,
			String reserved01) {
		this.economyNo = economyNo;
		this.economyName = economyName;
		this.reserved01 = reserved01;
	}

	public int getEconomyNo() {
		return this.economyNo;
	}

	public void setEconomyNo(int economyNo) {
		this.economyNo = economyNo;
	}

	public String getEconomyName() {
		return this.economyName;
	}

	public void setEconomyName(String economyName) {
		this.economyName = economyName;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

}
