package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

/**
 * RepTrainNewsView generated by hbm2java
 */
public class RepTrainNewsView implements java.io.Serializable {

	private RepTrainNewsViewId id;

	public RepTrainNewsView() {
	}

	public RepTrainNewsView(RepTrainNewsViewId id) {
		this.id = id;
	}

	public RepTrainNewsViewId getId() {
		return this.id;
	}

	public void setId(RepTrainNewsViewId id) {
		this.id = id;
	}

}
