package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RepUserResumeViewId generated by hbm2java
 */
public class RepUserResumeViewId implements java.io.Serializable {

	private int userNo;
	private String userUid;
	private String userPwd;
	private String userEmail;
	private String userName;
	private String userSex;
	private String userCert;
	private String userResidence;
	private Integer userAddrDisNo;
	private String userAddrPos;
	private String userIntentDisNo;
	private Integer userEducationNo;
	private Integer userExpNo;
	private Integer userIntentJobTypeNo;
	private String userIntention;
	private String userPhone;
	private Integer userAge;
	private String userBynow;
	private String userSkill;
	private String userContent;
	private String language;
	private String listen;
	private String write;
	private String corname;
	private String cornature;
	private String corscale;
	private String corindustry;
	private String department;
	private String report;
	private Integer subordinate;
	private String jobname;
	private Date worktime;
	private String workaddr;
	private String summary;
	private String jobperformance;
	private String studytime;
	private String school;
	private String objname;
	private String degree;
	private String entrance;
	private String pname;
	private String ptime;
	private String company;
	private String proJobname;
	private String proDescribe;
	private String pduty;
	private String jobgain;
	private String supInfo;
	private String supContent;
	private Date traintime;
	private String trainorgan;
	private String traincourse;
	private String certificate;
	private String describe;

	public RepUserResumeViewId() {
	}

	public RepUserResumeViewId(int userNo, String userUid, String userPwd,
			String userEmail, String corname) {
		this.userNo = userNo;
		this.userUid = userUid;
		this.userPwd = userPwd;
		this.userEmail = userEmail;
		this.corname = corname;
	}

	public RepUserResumeViewId(int userNo, String userUid, String userPwd,
			String userEmail, String userName, String userSex, String userCert,
			String userResidence, Integer userAddrDisNo, String userAddrPos,
			String userIntentDisNo, Integer userEducationNo, Integer userExpNo,
			Integer userIntentJobTypeNo, String userIntention,
			String userPhone, Integer userAge, String userBynow,
			String userSkill, String userContent, String language,
			String listen, String write, String corname, String cornature,
			String corscale, String corindustry, String department,
			String report, Integer subordinate, String jobname, Date worktime,
			String workaddr, String summary, String jobperformance,
			String studytime, String school, String objname, String degree,
			String entrance, String pname, String ptime, String company,
			String proJobname, String proDescribe, String pduty,
			String jobgain, String supInfo, String supContent, Date traintime,
			String trainorgan, String traincourse, String certificate,
			String describe) {
		this.userNo = userNo;
		this.userUid = userUid;
		this.userPwd = userPwd;
		this.userEmail = userEmail;
		this.userName = userName;
		this.userSex = userSex;
		this.userCert = userCert;
		this.userResidence = userResidence;
		this.userAddrDisNo = userAddrDisNo;
		this.userAddrPos = userAddrPos;
		this.userIntentDisNo = userIntentDisNo;
		this.userEducationNo = userEducationNo;
		this.userExpNo = userExpNo;
		this.userIntentJobTypeNo = userIntentJobTypeNo;
		this.userIntention = userIntention;
		this.userPhone = userPhone;
		this.userAge = userAge;
		this.userBynow = userBynow;
		this.userSkill = userSkill;
		this.userContent = userContent;
		this.language = language;
		this.listen = listen;
		this.write = write;
		this.corname = corname;
		this.cornature = cornature;
		this.corscale = corscale;
		this.corindustry = corindustry;
		this.department = department;
		this.report = report;
		this.subordinate = subordinate;
		this.jobname = jobname;
		this.worktime = worktime;
		this.workaddr = workaddr;
		this.summary = summary;
		this.jobperformance = jobperformance;
		this.studytime = studytime;
		this.school = school;
		this.objname = objname;
		this.degree = degree;
		this.entrance = entrance;
		this.pname = pname;
		this.ptime = ptime;
		this.company = company;
		this.proJobname = proJobname;
		this.proDescribe = proDescribe;
		this.pduty = pduty;
		this.jobgain = jobgain;
		this.supInfo = supInfo;
		this.supContent = supContent;
		this.traintime = traintime;
		this.trainorgan = trainorgan;
		this.traincourse = traincourse;
		this.certificate = certificate;
		this.describe = describe;
	}

	public int getUserNo() {
		return this.userNo;
	}

	public void setUserNo(int userNo) {
		this.userNo = userNo;
	}

	public String getUserUid() {
		return this.userUid;
	}

	public void setUserUid(String userUid) {
		this.userUid = userUid;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	public String getUserCert() {
		return this.userCert;
	}

	public void setUserCert(String userCert) {
		this.userCert = userCert;
	}

	public String getUserResidence() {
		return this.userResidence;
	}

	public void setUserResidence(String userResidence) {
		this.userResidence = userResidence;
	}

	public Integer getUserAddrDisNo() {
		return this.userAddrDisNo;
	}

	public void setUserAddrDisNo(Integer userAddrDisNo) {
		this.userAddrDisNo = userAddrDisNo;
	}

	public String getUserAddrPos() {
		return this.userAddrPos;
	}

	public void setUserAddrPos(String userAddrPos) {
		this.userAddrPos = userAddrPos;
	}

	public String getUserIntentDisNo() {
		return this.userIntentDisNo;
	}

	public void setUserIntentDisNo(String userIntentDisNo) {
		this.userIntentDisNo = userIntentDisNo;
	}

	public Integer getUserEducationNo() {
		return this.userEducationNo;
	}

	public void setUserEducationNo(Integer userEducationNo) {
		this.userEducationNo = userEducationNo;
	}

	public Integer getUserExpNo() {
		return this.userExpNo;
	}

	public void setUserExpNo(Integer userExpNo) {
		this.userExpNo = userExpNo;
	}

	public Integer getUserIntentJobTypeNo() {
		return this.userIntentJobTypeNo;
	}

	public void setUserIntentJobTypeNo(Integer userIntentJobTypeNo) {
		this.userIntentJobTypeNo = userIntentJobTypeNo;
	}

	public String getUserIntention() {
		return this.userIntention;
	}

	public void setUserIntention(String userIntention) {
		this.userIntention = userIntention;
	}

	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public Integer getUserAge() {
		return this.userAge;
	}

	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	public String getUserBynow() {
		return this.userBynow;
	}

	public void setUserBynow(String userBynow) {
		this.userBynow = userBynow;
	}

	public String getUserSkill() {
		return this.userSkill;
	}

	public void setUserSkill(String userSkill) {
		this.userSkill = userSkill;
	}

	public String getUserContent() {
		return this.userContent;
	}

	public void setUserContent(String userContent) {
		this.userContent = userContent;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getListen() {
		return this.listen;
	}

	public void setListen(String listen) {
		this.listen = listen;
	}

	public String getWrite() {
		return this.write;
	}

	public void setWrite(String write) {
		this.write = write;
	}

	public String getCorname() {
		return this.corname;
	}

	public void setCorname(String corname) {
		this.corname = corname;
	}

	public String getCornature() {
		return this.cornature;
	}

	public void setCornature(String cornature) {
		this.cornature = cornature;
	}

	public String getCorscale() {
		return this.corscale;
	}

	public void setCorscale(String corscale) {
		this.corscale = corscale;
	}

	public String getCorindustry() {
		return this.corindustry;
	}

	public void setCorindustry(String corindustry) {
		this.corindustry = corindustry;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getReport() {
		return this.report;
	}

	public void setReport(String report) {
		this.report = report;
	}

	public Integer getSubordinate() {
		return this.subordinate;
	}

	public void setSubordinate(Integer subordinate) {
		this.subordinate = subordinate;
	}

	public String getJobname() {
		return this.jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

	public Date getWorktime() {
		return this.worktime;
	}

	public void setWorktime(Date worktime) {
		this.worktime = worktime;
	}

	public String getWorkaddr() {
		return this.workaddr;
	}

	public void setWorkaddr(String workaddr) {
		this.workaddr = workaddr;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getJobperformance() {
		return this.jobperformance;
	}

	public void setJobperformance(String jobperformance) {
		this.jobperformance = jobperformance;
	}

	public String getStudytime() {
		return this.studytime;
	}

	public void setStudytime(String studytime) {
		this.studytime = studytime;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getObjname() {
		return this.objname;
	}

	public void setObjname(String objname) {
		this.objname = objname;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getEntrance() {
		return this.entrance;
	}

	public void setEntrance(String entrance) {
		this.entrance = entrance;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPtime() {
		return this.ptime;
	}

	public void setPtime(String ptime) {
		this.ptime = ptime;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getProJobname() {
		return this.proJobname;
	}

	public void setProJobname(String proJobname) {
		this.proJobname = proJobname;
	}

	public String getProDescribe() {
		return this.proDescribe;
	}

	public void setProDescribe(String proDescribe) {
		this.proDescribe = proDescribe;
	}

	public String getPduty() {
		return this.pduty;
	}

	public void setPduty(String pduty) {
		this.pduty = pduty;
	}

	public String getJobgain() {
		return this.jobgain;
	}

	public void setJobgain(String jobgain) {
		this.jobgain = jobgain;
	}

	public String getSupInfo() {
		return this.supInfo;
	}

	public void setSupInfo(String supInfo) {
		this.supInfo = supInfo;
	}

	public String getSupContent() {
		return this.supContent;
	}

	public void setSupContent(String supContent) {
		this.supContent = supContent;
	}

	public Date getTraintime() {
		return this.traintime;
	}

	public void setTraintime(Date traintime) {
		this.traintime = traintime;
	}

	public String getTrainorgan() {
		return this.trainorgan;
	}

	public void setTrainorgan(String trainorgan) {
		this.trainorgan = trainorgan;
	}

	public String getTraincourse() {
		return this.traincourse;
	}

	public void setTraincourse(String traincourse) {
		this.traincourse = traincourse;
	}

	public String getCertificate() {
		return this.certificate;
	}

	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepUserResumeViewId))
			return false;
		RepUserResumeViewId castOther = (RepUserResumeViewId) other;

		return (this.getUserNo() == castOther.getUserNo())
				&& ((this.getUserUid() == castOther.getUserUid()) || (this
						.getUserUid() != null && castOther.getUserUid() != null && this
						.getUserUid().equals(castOther.getUserUid())))
				&& ((this.getUserPwd() == castOther.getUserPwd()) || (this
						.getUserPwd() != null && castOther.getUserPwd() != null && this
						.getUserPwd().equals(castOther.getUserPwd())))
				&& ((this.getUserEmail() == castOther.getUserEmail()) || (this
						.getUserEmail() != null
						&& castOther.getUserEmail() != null && this
						.getUserEmail().equals(castOther.getUserEmail())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserSex() == castOther.getUserSex()) || (this
						.getUserSex() != null && castOther.getUserSex() != null && this
						.getUserSex().equals(castOther.getUserSex())))
				&& ((this.getUserCert() == castOther.getUserCert()) || (this
						.getUserCert() != null
						&& castOther.getUserCert() != null && this
						.getUserCert().equals(castOther.getUserCert())))
				&& ((this.getUserResidence() == castOther.getUserResidence()) || (this
						.getUserResidence() != null
						&& castOther.getUserResidence() != null && this
						.getUserResidence()
						.equals(castOther.getUserResidence())))
				&& ((this.getUserAddrDisNo() == castOther.getUserAddrDisNo()) || (this
						.getUserAddrDisNo() != null
						&& castOther.getUserAddrDisNo() != null && this
						.getUserAddrDisNo()
						.equals(castOther.getUserAddrDisNo())))
				&& ((this.getUserAddrPos() == castOther.getUserAddrPos()) || (this
						.getUserAddrPos() != null
						&& castOther.getUserAddrPos() != null && this
						.getUserAddrPos().equals(castOther.getUserAddrPos())))
				&& ((this.getUserIntentDisNo() == castOther
						.getUserIntentDisNo()) || (this.getUserIntentDisNo() != null
						&& castOther.getUserIntentDisNo() != null && this
						.getUserIntentDisNo().equals(
								castOther.getUserIntentDisNo())))
				&& ((this.getUserEducationNo() == castOther
						.getUserEducationNo()) || (this.getUserEducationNo() != null
						&& castOther.getUserEducationNo() != null && this
						.getUserEducationNo().equals(
								castOther.getUserEducationNo())))
				&& ((this.getUserExpNo() == castOther.getUserExpNo()) || (this
						.getUserExpNo() != null
						&& castOther.getUserExpNo() != null && this
						.getUserExpNo().equals(castOther.getUserExpNo())))
				&& ((this.getUserIntentJobTypeNo() == castOther
						.getUserIntentJobTypeNo()) || (this
						.getUserIntentJobTypeNo() != null
						&& castOther.getUserIntentJobTypeNo() != null && this
						.getUserIntentJobTypeNo().equals(
								castOther.getUserIntentJobTypeNo())))
				&& ((this.getUserIntention() == castOther.getUserIntention()) || (this
						.getUserIntention() != null
						&& castOther.getUserIntention() != null && this
						.getUserIntention()
						.equals(castOther.getUserIntention())))
				&& ((this.getUserPhone() == castOther.getUserPhone()) || (this
						.getUserPhone() != null
						&& castOther.getUserPhone() != null && this
						.getUserPhone().equals(castOther.getUserPhone())))
				&& ((this.getUserAge() == castOther.getUserAge()) || (this
						.getUserAge() != null && castOther.getUserAge() != null && this
						.getUserAge().equals(castOther.getUserAge())))
				&& ((this.getUserBynow() == castOther.getUserBynow()) || (this
						.getUserBynow() != null
						&& castOther.getUserBynow() != null && this
						.getUserBynow().equals(castOther.getUserBynow())))
				&& ((this.getUserSkill() == castOther.getUserSkill()) || (this
						.getUserSkill() != null
						&& castOther.getUserSkill() != null && this
						.getUserSkill().equals(castOther.getUserSkill())))
				&& ((this.getUserContent() == castOther.getUserContent()) || (this
						.getUserContent() != null
						&& castOther.getUserContent() != null && this
						.getUserContent().equals(castOther.getUserContent())))
				&& ((this.getLanguage() == castOther.getLanguage()) || (this
						.getLanguage() != null
						&& castOther.getLanguage() != null && this
						.getLanguage().equals(castOther.getLanguage())))
				&& ((this.getListen() == castOther.getListen()) || (this
						.getListen() != null && castOther.getListen() != null && this
						.getListen().equals(castOther.getListen())))
				&& ((this.getWrite() == castOther.getWrite()) || (this
						.getWrite() != null && castOther.getWrite() != null && this
						.getWrite().equals(castOther.getWrite())))
				&& ((this.getCorname() == castOther.getCorname()) || (this
						.getCorname() != null && castOther.getCorname() != null && this
						.getCorname().equals(castOther.getCorname())))
				&& ((this.getCornature() == castOther.getCornature()) || (this
						.getCornature() != null
						&& castOther.getCornature() != null && this
						.getCornature().equals(castOther.getCornature())))
				&& ((this.getCorscale() == castOther.getCorscale()) || (this
						.getCorscale() != null
						&& castOther.getCorscale() != null && this
						.getCorscale().equals(castOther.getCorscale())))
				&& ((this.getCorindustry() == castOther.getCorindustry()) || (this
						.getCorindustry() != null
						&& castOther.getCorindustry() != null && this
						.getCorindustry().equals(castOther.getCorindustry())))
				&& ((this.getDepartment() == castOther.getDepartment()) || (this
						.getDepartment() != null
						&& castOther.getDepartment() != null && this
						.getDepartment().equals(castOther.getDepartment())))
				&& ((this.getReport() == castOther.getReport()) || (this
						.getReport() != null && castOther.getReport() != null && this
						.getReport().equals(castOther.getReport())))
				&& ((this.getSubordinate() == castOther.getSubordinate()) || (this
						.getSubordinate() != null
						&& castOther.getSubordinate() != null && this
						.getSubordinate().equals(castOther.getSubordinate())))
				&& ((this.getJobname() == castOther.getJobname()) || (this
						.getJobname() != null && castOther.getJobname() != null && this
						.getJobname().equals(castOther.getJobname())))
				&& ((this.getWorktime() == castOther.getWorktime()) || (this
						.getWorktime() != null
						&& castOther.getWorktime() != null && this
						.getWorktime().equals(castOther.getWorktime())))
				&& ((this.getWorkaddr() == castOther.getWorkaddr()) || (this
						.getWorkaddr() != null
						&& castOther.getWorkaddr() != null && this
						.getWorkaddr().equals(castOther.getWorkaddr())))
				&& ((this.getSummary() == castOther.getSummary()) || (this
						.getSummary() != null && castOther.getSummary() != null && this
						.getSummary().equals(castOther.getSummary())))
				&& ((this.getJobperformance() == castOther.getJobperformance()) || (this
						.getJobperformance() != null
						&& castOther.getJobperformance() != null && this
						.getJobperformance().equals(
								castOther.getJobperformance())))
				&& ((this.getStudytime() == castOther.getStudytime()) || (this
						.getStudytime() != null
						&& castOther.getStudytime() != null && this
						.getStudytime().equals(castOther.getStudytime())))
				&& ((this.getSchool() == castOther.getSchool()) || (this
						.getSchool() != null && castOther.getSchool() != null && this
						.getSchool().equals(castOther.getSchool())))
				&& ((this.getObjname() == castOther.getObjname()) || (this
						.getObjname() != null && castOther.getObjname() != null && this
						.getObjname().equals(castOther.getObjname())))
				&& ((this.getDegree() == castOther.getDegree()) || (this
						.getDegree() != null && castOther.getDegree() != null && this
						.getDegree().equals(castOther.getDegree())))
				&& ((this.getEntrance() == castOther.getEntrance()) || (this
						.getEntrance() != null
						&& castOther.getEntrance() != null && this
						.getEntrance().equals(castOther.getEntrance())))
				&& ((this.getPname() == castOther.getPname()) || (this
						.getPname() != null && castOther.getPname() != null && this
						.getPname().equals(castOther.getPname())))
				&& ((this.getPtime() == castOther.getPtime()) || (this
						.getPtime() != null && castOther.getPtime() != null && this
						.getPtime().equals(castOther.getPtime())))
				&& ((this.getCompany() == castOther.getCompany()) || (this
						.getCompany() != null && castOther.getCompany() != null && this
						.getCompany().equals(castOther.getCompany())))
				&& ((this.getProJobname() == castOther.getProJobname()) || (this
						.getProJobname() != null
						&& castOther.getProJobname() != null && this
						.getProJobname().equals(castOther.getProJobname())))
				&& ((this.getProDescribe() == castOther.getProDescribe()) || (this
						.getProDescribe() != null
						&& castOther.getProDescribe() != null && this
						.getProDescribe().equals(castOther.getProDescribe())))
				&& ((this.getPduty() == castOther.getPduty()) || (this
						.getPduty() != null && castOther.getPduty() != null && this
						.getPduty().equals(castOther.getPduty())))
				&& ((this.getJobgain() == castOther.getJobgain()) || (this
						.getJobgain() != null && castOther.getJobgain() != null && this
						.getJobgain().equals(castOther.getJobgain())))
				&& ((this.getSupInfo() == castOther.getSupInfo()) || (this
						.getSupInfo() != null && castOther.getSupInfo() != null && this
						.getSupInfo().equals(castOther.getSupInfo())))
				&& ((this.getSupContent() == castOther.getSupContent()) || (this
						.getSupContent() != null
						&& castOther.getSupContent() != null && this
						.getSupContent().equals(castOther.getSupContent())))
				&& ((this.getTraintime() == castOther.getTraintime()) || (this
						.getTraintime() != null
						&& castOther.getTraintime() != null && this
						.getTraintime().equals(castOther.getTraintime())))
				&& ((this.getTrainorgan() == castOther.getTrainorgan()) || (this
						.getTrainorgan() != null
						&& castOther.getTrainorgan() != null && this
						.getTrainorgan().equals(castOther.getTrainorgan())))
				&& ((this.getTraincourse() == castOther.getTraincourse()) || (this
						.getTraincourse() != null
						&& castOther.getTraincourse() != null && this
						.getTraincourse().equals(castOther.getTraincourse())))
				&& ((this.getCertificate() == castOther.getCertificate()) || (this
						.getCertificate() != null
						&& castOther.getCertificate() != null && this
						.getCertificate().equals(castOther.getCertificate())))
				&& ((this.getDescribe() == castOther.getDescribe()) || (this
						.getDescribe() != null
						&& castOther.getDescribe() != null && this
						.getDescribe().equals(castOther.getDescribe())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserNo();
		result = 37 * result
				+ (getUserUid() == null ? 0 : this.getUserUid().hashCode());
		result = 37 * result
				+ (getUserPwd() == null ? 0 : this.getUserPwd().hashCode());
		result = 37 * result
				+ (getUserEmail() == null ? 0 : this.getUserEmail().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getUserSex() == null ? 0 : this.getUserSex().hashCode());
		result = 37 * result
				+ (getUserCert() == null ? 0 : this.getUserCert().hashCode());
		result = 37
				* result
				+ (getUserResidence() == null ? 0 : this.getUserResidence()
						.hashCode());
		result = 37
				* result
				+ (getUserAddrDisNo() == null ? 0 : this.getUserAddrDisNo()
						.hashCode());
		result = 37
				* result
				+ (getUserAddrPos() == null ? 0 : this.getUserAddrPos()
						.hashCode());
		result = 37
				* result
				+ (getUserIntentDisNo() == null ? 0 : this.getUserIntentDisNo()
						.hashCode());
		result = 37
				* result
				+ (getUserEducationNo() == null ? 0 : this.getUserEducationNo()
						.hashCode());
		result = 37 * result
				+ (getUserExpNo() == null ? 0 : this.getUserExpNo().hashCode());
		result = 37
				* result
				+ (getUserIntentJobTypeNo() == null ? 0 : this
						.getUserIntentJobTypeNo().hashCode());
		result = 37
				* result
				+ (getUserIntention() == null ? 0 : this.getUserIntention()
						.hashCode());
		result = 37 * result
				+ (getUserPhone() == null ? 0 : this.getUserPhone().hashCode());
		result = 37 * result
				+ (getUserAge() == null ? 0 : this.getUserAge().hashCode());
		result = 37 * result
				+ (getUserBynow() == null ? 0 : this.getUserBynow().hashCode());
		result = 37 * result
				+ (getUserSkill() == null ? 0 : this.getUserSkill().hashCode());
		result = 37
				* result
				+ (getUserContent() == null ? 0 : this.getUserContent()
						.hashCode());
		result = 37 * result
				+ (getLanguage() == null ? 0 : this.getLanguage().hashCode());
		result = 37 * result
				+ (getListen() == null ? 0 : this.getListen().hashCode());
		result = 37 * result
				+ (getWrite() == null ? 0 : this.getWrite().hashCode());
		result = 37 * result
				+ (getCorname() == null ? 0 : this.getCorname().hashCode());
		result = 37 * result
				+ (getCornature() == null ? 0 : this.getCornature().hashCode());
		result = 37 * result
				+ (getCorscale() == null ? 0 : this.getCorscale().hashCode());
		result = 37
				* result
				+ (getCorindustry() == null ? 0 : this.getCorindustry()
						.hashCode());
		result = 37
				* result
				+ (getDepartment() == null ? 0 : this.getDepartment()
						.hashCode());
		result = 37 * result
				+ (getReport() == null ? 0 : this.getReport().hashCode());
		result = 37
				* result
				+ (getSubordinate() == null ? 0 : this.getSubordinate()
						.hashCode());
		result = 37 * result
				+ (getJobname() == null ? 0 : this.getJobname().hashCode());
		result = 37 * result
				+ (getWorktime() == null ? 0 : this.getWorktime().hashCode());
		result = 37 * result
				+ (getWorkaddr() == null ? 0 : this.getWorkaddr().hashCode());
		result = 37 * result
				+ (getSummary() == null ? 0 : this.getSummary().hashCode());
		result = 37
				* result
				+ (getJobperformance() == null ? 0 : this.getJobperformance()
						.hashCode());
		result = 37 * result
				+ (getStudytime() == null ? 0 : this.getStudytime().hashCode());
		result = 37 * result
				+ (getSchool() == null ? 0 : this.getSchool().hashCode());
		result = 37 * result
				+ (getObjname() == null ? 0 : this.getObjname().hashCode());
		result = 37 * result
				+ (getDegree() == null ? 0 : this.getDegree().hashCode());
		result = 37 * result
				+ (getEntrance() == null ? 0 : this.getEntrance().hashCode());
		result = 37 * result
				+ (getPname() == null ? 0 : this.getPname().hashCode());
		result = 37 * result
				+ (getPtime() == null ? 0 : this.getPtime().hashCode());
		result = 37 * result
				+ (getCompany() == null ? 0 : this.getCompany().hashCode());
		result = 37
				* result
				+ (getProJobname() == null ? 0 : this.getProJobname()
						.hashCode());
		result = 37
				* result
				+ (getProDescribe() == null ? 0 : this.getProDescribe()
						.hashCode());
		result = 37 * result
				+ (getPduty() == null ? 0 : this.getPduty().hashCode());
		result = 37 * result
				+ (getJobgain() == null ? 0 : this.getJobgain().hashCode());
		result = 37 * result
				+ (getSupInfo() == null ? 0 : this.getSupInfo().hashCode());
		result = 37
				* result
				+ (getSupContent() == null ? 0 : this.getSupContent()
						.hashCode());
		result = 37 * result
				+ (getTraintime() == null ? 0 : this.getTraintime().hashCode());
		result = 37
				* result
				+ (getTrainorgan() == null ? 0 : this.getTrainorgan()
						.hashCode());
		result = 37
				* result
				+ (getTraincourse() == null ? 0 : this.getTraincourse()
						.hashCode());
		result = 37
				* result
				+ (getCertificate() == null ? 0 : this.getCertificate()
						.hashCode());
		result = 37 * result
				+ (getDescribe() == null ? 0 : this.getDescribe().hashCode());
		return result;
	}

}
