package com.ree.hibernate;

// Generated 2015-1-23 22:08:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RepEntAuditionUser generated by hbm2java
 */
public class RepEntAuditionUser implements java.io.Serializable {

	private RepEntAuditionUserId id;
	private Date auditionTime;
	private String auditionAddr;
	private int state;
	private Date submittime;
	private String memo;
	private String reserved01;

	public RepEntAuditionUser() {
	}

	public RepEntAuditionUser(RepEntAuditionUserId id, Date auditionTime,
			String auditionAddr, int state, Date submittime) {
		this.id = id;
		this.auditionTime = auditionTime;
		this.auditionAddr = auditionAddr;
		this.state = state;
		this.submittime = submittime;
	}

	public RepEntAuditionUser(RepEntAuditionUserId id, Date auditionTime,
			String auditionAddr, int state, Date submittime, String memo,
			String reserved01) {
		this.id = id;
		this.auditionTime = auditionTime;
		this.auditionAddr = auditionAddr;
		this.state = state;
		this.submittime = submittime;
		this.memo = memo;
		this.reserved01 = reserved01;
	}

	public RepEntAuditionUserId getId() {
		return this.id;
	}

	public void setId(RepEntAuditionUserId id) {
		this.id = id;
	}

	public Date getAuditionTime() {
		return this.auditionTime;
	}

	public void setAuditionTime(Date auditionTime) {
		this.auditionTime = auditionTime;
	}

	public String getAuditionAddr() {
		return this.auditionAddr;
	}

	public void setAuditionAddr(String auditionAddr) {
		this.auditionAddr = auditionAddr;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getSubmittime() {
		return this.submittime;
	}

	public void setSubmittime(Date submittime) {
		this.submittime = submittime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

}
